-- Group A, Group B
INSERT INTO AIRSHIPS (AIRSHIP_ID, NAME, AIRSHIP_SPEED, HULL_POINTS, ARMOR_VALUE, DAMAGE_STATE) VALUES (1, 'Queen Zaza', 70, 121, 4, 'IN_ORDER');
INSERT INTO AIRSHIPS (AIRSHIP_ID, NAME, AIRSHIP_SPEED, HULL_POINTS, ARMOR_VALUE, DAMAGE_STATE) VALUES (2, 'Adamant', 40, 64, 5, 'DAMAGED');
INSERT INTO AIRSHIPS (AIRSHIP_ID, NAME, AIRSHIP_SPEED, HULL_POINTS, ARMOR_VALUE, DAMAGE_STATE) VALUES (3, 'Arkanaut Ironclad', 85, 420, 2, 'IN_ORDER');

-- only Group A
INSERT INTO ENGINES_ST (ENGINE_ID, POWER_TYPE, ENGINE_TYPE, ENGINE_LABEL) VALUES (1, 'MEDIUM',  'COMBUSTION', 'Mucha 3V');
INSERT INTO ENGINES_ST (ENGINE_ID, POWER_TYPE, ENGINE_TYPE, ENGINE_LABEL) VALUES (3, 'LOW',  'STEAM', 'Macho Desaster TZ5');
INSERT INTO ENGINES_ST (ENGINE_ID, POWER_TYPE, ENGINE_TYPE, ENGINE_LABEL) VALUES (6, 'HIGH',  'JET', 'FDD 45');

-- only Groub B
INSERT INTO WEAPONS_ST (WEAPON_ID, NAME, ATTACK_VALUE, AMMONITION_CAPACITY, `RANGE`, WEAPON_TYPE) VALUES (1, 'Battlecannon', 3, 200, 'MEDIUM', 'RAPID_FIRE');
INSERT INTO WEAPONS_ST (WEAPON_ID, NAME, ATTACK_VALUE, AMMONITION_CAPACITY, `RANGE`, WEAPON_TYPE) VALUES (2, 'Ground Bomb', 4, 4, 'SHORT', 'BOMB');
INSERT INTO WEAPONS_ST (WEAPON_ID, NAME, ATTACK_VALUE, AMMONITION_CAPACITY, `RANGE`, WEAPON_TYPE) VALUES (3, 'Gatlinggun', 2, 400, 'MEDIUM', 'RAPID_FIRE');



